# /qompassai/rust/.cargo/config.toml
# Qompass AI Rust Cargo Template
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################

[build]
pipelining = true
jobs = 4

[alias]
b = "build"
r = "run"
t = "test"
zig-x86_64-release = "cargo zigbuild --release --target x86_64-unknown-linux-gnu"
zig-aarch64-release = "cargo zigbuild --release --target aarch64-unknown-linux-gnu"
zigtest-aarch64 = "cargo zigbuild test --target aarch64-unknown-linux-gnu"
zigrun-aarch64 = "cargo zigbuild run --target aarch64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C",
  "link-arg=--target=x86_64-linux-gnu",
  "-C",
  "link-arg=-fuse-ld=lld",
]

[target.aarch64-unknown-linux-gnu]
cc = "zig cc -target aarch64-unknown-linux-gnu"
linker = "zig cc -target aarch64-unknown-linux-gnu"

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "link-arg=-target=x86_64-linux-musl"]

[env]
SCCACHE_DIR = "/home/phaedrus/.local/bin/sccache"
SCCACHE_IDLE_TIMEOUT = "1200"
CARGO_INCREMENTAL = "0"
CARGO_ZIGBUILD_RELEASE = "true"
CARGO_ZIGBUILD_VERBOSE = "true"
ZIG_TARGET_DIR = "/home/phaedrus/.cache/target"
ZIG_GLOBAL_CACHE_DIR = "/home/phaedrus/.cache/zig"

[registries.crates-io]
protocol = "sparse"

[registry]
default = "crates-io"

[term]
verbose = true
quiet = false
color = 'auto'
hyperlinks = true
unicode = true
progress.when = 'auto'
progress.width = 80
progress.term-integration = true

[future-incompat-report]
frequency = "always"

[http]
debug = false
ssl-version = "tlsv1.3"
timeout = 60

[net]
retry = 3

[net.ssh]
known-hosts = ["..."]
